kind: List
apiVersion: v1
metadata:
  name: s2i-devonfw
items:
- kind: Template
  apiVersion: v1
  metadata:
    name: devonfw-angular
    annotations:
      description: DevonFW application (angular/front-end)
      openshift.io/display-name: DevonFW Angular
      iconClass: devonfw-angular-logo
      tags: instant-app,devonfw,javascript,angular
  labels:
    createdBy: devonfw-angular
  parameters:
  - description: 'The name for the application. It can''t contain whitespaces. It
      should be the app name including technology, example: mythaistar-angular'
    name: APPLICATION_NAME
    displayName: Application name
    required: true
  - description: 'The name for the group list of applications. It can''t contain whitespaces.
      It should be the app name excluding technology, example: My-Thai-Star'
    name: APPLICATION_GROUP_NAME
    displayName: Application group name
    required: true
  - description: 'Custom hostname for service routes. Leave blank for default hostname,
      e.g.: <application-name>.<project>.<default-domain-suffix>'
    name: APPLICATION_HOSTNAME
    displayName: Application hostname
  - description: The pattern URL of the backend's REST API endpoint inside the source
      code that is supposed to be modified by the REST Endpoint URL field.
    name: REST_ENDPOINT_PATTERN
    displayName: REST Endpoint PATTERN URL
    value: http://localhost:8081
  - description: The URL of the backend's REST API endpoint
    name: REST_ENDPOINT_URL
    displayName: REST Endpoint URL
  - description: 'Git source URI for application, example: https://github.com/oasp/my-thai-star.git'
    name: GIT_URI
    displayName: Git repository URI
    required: true
  - description: 'Git branch/tag reference, example: develop'
    name: GIT_REF
    displayName: Git repository BRANCH
    required: true
  - description: 'Git directory context, example: /angular'
    name: CONTEXT_DIR
    displayName: Git repository CONTEXT
  - description: Github trigger secret
    name: GITHUB_TRIGGER_SECRET
    from: "[a-zA-Z0-9]{8}"
    generate: expression
  - description: Generic build trigger secret
    name: GENERIC_TRIGGER_SECRET
    from: "[a-zA-Z0-9]{8}"
    generate: expression
  objects:
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: "${APPLICATION_NAME}"
      labels:
        app: "${APPLICATION_GROUP_NAME}"
        application: "${APPLICATION_NAME}"
    spec:
      triggers:
      - type: GitHub
        github:
          secret: "${GITHUB_TRIGGER_SECRET}"
      - type: Generic
        generic:
          secret: "${GENERIC_TRIGGER_SECRET}"
      - type: ImageChange
        imageChange: {}
      source:
        type: Git
        git:
          uri: "${GIT_URI}"
          ref: "${GIT_REF}"
        contextDir: "${CONTEXT_DIR}"
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            namespace: devonfw
            name: s2i-devonfw-angular:latest
          env:
          - name: REST_ENDPOINT_URL
            value: "${REST_ENDPOINT_URL}"
          - name: REST_ENDPOINT_PATTERN
            value: "${REST_ENDPOINT_PATTERN}"
          - name: BUILD_TARGET
            value: prod
          - name: ARTIFACT_DIR
            value: dist
      output:
        to:
          kind: ImageStreamTag
          name: "${APPLICATION_NAME}:latest"
      resources: {}
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: "${APPLICATION_NAME}"
      labels:
        app: "${APPLICATION_GROUP_NAME}"
        application: "${APPLICATION_NAME}"
    spec:
      dockerImageRepository: ''
      tags:
      - name: latest
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: "${APPLICATION_NAME}"
      labels:
        app: "${APPLICATION_GROUP_NAME}"
        application: "${APPLICATION_NAME}"
    spec:
      strategy:
        type: Rolling
        rollingParams:
          updatePeriodSeconds: 1
          intervalSeconds: 1
          timeoutSeconds: 600
        resources: {}
      triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
          - "${APPLICATION_NAME}"
          from:
            kind: ImageStreamTag
            name: "${APPLICATION_NAME}:latest"
      replicas: 1
      selector:
        deploymentconfig: "${APPLICATION_NAME}"
      template:
        metadata:
          labels:
            deploymentconfig: "${APPLICATION_NAME}"
        spec:
          containers:
          - name: "${APPLICATION_NAME}"
            image: "${APPLICATION_NAME}"
            ports:
            - containerPort: 8080
              protocol: TCP
            resources: {}
            terminationMessagePath: "/dev/termination-log"
            imagePullPolicy: IfNotPresent
            securityContext:
              capabilities: {}
              privileged: false
          restartPolicy: Always
          dnsPolicy: ClusterFirst
  - kind: Route
    apiVersion: v1
    metadata:
      name: "${APPLICATION_NAME}"
      labels:
        app: "${APPLICATION_GROUP_NAME}"
        application: "${APPLICATION_NAME}"
    spec:
      host: "${APPLICATION_HOSTNAME}"
      to:
        kind: Service
        name: "${APPLICATION_NAME}"
  - kind: Service
    apiVersion: v1
    metadata:
      name: "${APPLICATION_NAME}"
      labels:
        app: "${APPLICATION_GROUP_NAME}"
        application: "${APPLICATION_NAME}"
    spec:
      ports:
      - name: "${APPLICATION_NAME}-http"
        port: 8091
        targetPort: 8080
      selector:
        deploymentconfig: "${APPLICATION_NAME}"
      type: ClusterIP
      sessionAffinity: None